# Generated by Django 5.0.7 on 2026-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="contact_click_count",
            field=models.IntegerField(default=0),
        ),
    ]
