# Generated by Django 5.0.7 on 2026-04-12 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_subscription_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="id_card_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="verification/id_cards/"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="registration_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="selfie_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="verification/selfies/"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="verification_submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="student_id",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Not Verified"),
                    ("pending", "Pending Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmailOTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_hash", models.CharField(max_length=64)),
                ("otp_created_at", models.DateTimeField()),
                ("otp_expires_at", models.DateTimeField()),
                ("attempts", models.IntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("resend_count", models.IntegerField(default=0)),
                ("last_resent_at", models.DateTimeField(blank=True, null=True)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_otp",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
