# Generated by Django 5.0.7 on 2026-04-12 21:40

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_customuser_id_card_photo_customuser_registration_ip_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingVerificationProxy",
            fields=[],
            options={
                "verbose_name": "Pending Verification",
                "verbose_name_plural": "Pending Verifications",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.customuser",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_manage_payments", "Can manage subscription payments"),
                    ("can_review_verifications", "Can review identity verifications"),
                ],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
    ]
