# Generated by Django 5.0.7 on 2026-03-23 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        ("skills", "0002_add_language_to_skill_offering"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="skill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="skills.skilloffering",
            ),
        ),
    ]
