# Generated by Django 6.0.3 on 2026-03-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skilloffering",
            name="language",
            field=models.CharField(
                blank=True,
                default="English",
                help_text='e.g. "English, Luganda, Swahili"',
                max_length=200,
            ),
        ),
    ]
