# Generated by Django 6.0.3 on 2026-03-22 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_message", "New Message"),
                            ("booking_request", "Booking Request"),
                            ("booking_accepted", "Booking Accepted"),
                            ("booking_declined", "Booking Declined"),
                            ("booking_completed", "Booking Completed"),
                            ("item_sold", "Item Marked as Sold"),
                            ("new_review", "New Review Received"),
                            ("listing_reported", "Listing Reported"),
                            ("account_verified", "Account Verified"),
                            ("price_drop", "Price Drop on Saved Item"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
